fastlane_version "2.196.0"

default_platform :ios

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    snapshot(localize_simulator: true, dark_mode: true, launch_arguments: "DARK_MODE", clear_previous_screenshots: true)
    snapshot(localize_simulator: true, dark_mode: false)
    gym(include_bitcode: true)
    deliver(force: true)
  end
end
